### ISSUE TITLE
when you dont use intellij create gradle project

### ISSUE THREAD

**Issue by xf8b** [KingRealzYT/TerrariaModBot#1]

**Comment by KingRealzYT** [comment]
i used gradle init, got a problem?

**Comment by xf8b** [comment]
utilities subproject random other shit

**Comment by KingRealzYT** [comment]
k

**Comment by KingRealzYT** [comment]
is this a suggestion?

**Comment by xf8b** [comment]
kkioju fdrktflgu;hijokl

**Comment by KingRealzYT** [comment]
are you suggesting me to redo it with intellij gradle project, cause i'll do it

**Comment by xf8b** [comment]
itrestaeretsyrutyu8908y5t

**Comment by KingRealzYT** [comment]
counting that as a yes
